DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(255),
  picture_url VARCHAR(255),
  isAdmin BOOLEAN,
);
